spring.application.name=transactionms


server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/transactionmsdb?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=8188mlbs

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=ThisIsMySecretKeyForJwtTokenGeneration123456
jwt.expiration=86400000